wipe = true
pkgname = "models"
output = "internal/models"

[crdb]
dbname = "tenant_api_dev"
host = "crdb"
port = 26257
user = "root"
sslmode = "disable"
blacklist = ["goose_db_version"]

[[types]]
    [types.match]
        name = "id"
        nullable = false
    [types.replace]
        type = "gidx.PrefixedID"
    [types.imports]
        third_party = ['"go.infratographer.com/x/gidx"']
[[types]]
    [types.match]
        name = "parent_tenant_id"
        nullable = true
    [types.replace]
        type = "nullx.PrefixedID"
    [types.imports]
        third_party = ['"go.infratographer.com/tenant-api/internal/x/nullx"']
