// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"go.infratographer.com/tenant-api/internal/ent/generated"
)

// Return response from tenantCreate
type TenantCreatePayload struct {
	// The created tenant.
	Tenant *generated.Tenant `json:"tenant"`
}
