---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.api.extraLabels }}
    {{- toYaml .Values.api.extraLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.api.extraAnnotations }}
  annotations:
    {{- toYaml .Values.api.extraAnnotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.labels.standard" . | nindent 8 }}
      {{- if .Values.api.extraLabels }}
      {{- toYaml .Values.api.extraLabels | nindent 8 }}
      {{- end }}
      annotations: {{- include "iam-runtime-infratographer.annotations" $ | nindent 8 }}
      {{- if .Values.api.extraAnnotations }}
        {{- toYaml .Values.api.extraAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.api.db.migrateOnInit  }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          envFrom:
            - secretRef:
                name: {{ .Values.api.db.uriSecret }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - up
          volumeMounts:
            {{- if .Values.api.db.certSecret }}
            - name: dbcerts
              mountPath: "{{ .Values.api.db.certMountPath }}"
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: TENANTAPI_SERVER_LISTEN
              value: ":{{ .Values.api.listenPort }}"
            - name: TENANTAPI_SERVER_SHUTDOWN_GRACE_PERIOD
              value: "{{ .Values.api.shutdownGracePeriod }}"
            - name: TENANTAPI_TRACING_ENABLED
              value: "{{ .Values.api.tracing.enabled }}"
            - name: TENANTAPI_TRACING_PROVIDER
              value: "{{ .Values.api.tracing.provider }}"
            - name: TENANTAPI_TRACING_ENVIRONMENT
              value: "{{ .Values.api.tracing.environment }}"
          {{- if eq .Values.api.tracing.provider "jaeger" }}
            - name: TENANTAPI_TRACING_JAEGER_ENDPOINT
              value: "{{ .Values.api.tracing.jaeger.endpoint }}"
            - name: TENANTAPI_TRACING_JAEGER_USER
              value: "{{ .Values.api.tracing.jaeger.user }}"
            - name: TENANTAPI_TRACING_JAEGER_PASSWORD
              value: "{{ .Values.api.tracing.jaeger.password }}"
          {{- end }}
          {{- if eq .Values.api.tracing.provider "otlpgrpc" }}
            - name: TENANTAPI_TRACING_OTLP_ENDPOINT
              value: "{{ .Values.api.tracing.otlp.endpoint }}"
            - name: TENANTAPI_TRACING_OTLP_INSECURE
              value: "{{ .Values.api.tracing.otlp.insecure }}"
            - name: TENANTAPI_TRACING_OTLP_CERTIFICATE
              value: "{{ .Values.api.tracing.otlp.certificate }}"
          {{- end }}
          {{- with .Values.api.trustedProxies }}
            - name: TENANTAPI_SERVER_TRUSTED_PROXIES
              value: "{{ join " " . }}"
          {{- end }}
            - name: TENANTAPI_EVENTS_NATS_URL
              value: "{{ .Values.api.events.nats.url }}"
            - name: TENANTAPI_EVENTS_NATS_PUBLISHPREFIX
              value: "{{ .Values.api.events.nats.publishPrefix }}"
            - name: TENANTAPI_EVENTS_NATS_QUEUEGROUP
              value: "{{ .Values.api.events.nats.queueGroup }}"
            - name: TENANTAPI_EVENTS_NATS_SOURCE
              value: "{{ .Values.api.events.nats.source }}"
            - name: TENANTAPI_EVENTS_NATS_CONNECTTIMEOUT
              value: "{{ .Values.api.events.nats.connectTimeout }}"
            - name: TENANTAPI_EVENTS_NATS_SHUTDOWNTIMEOUT
              value: "{{ .Values.api.events.nats.shutdownTimeout }}"
          {{- with .Values.api.events.topics }}
            - name: TENANTAPI_EVENTS_TOPICS
              value: "{{ join " " . }}"
          {{- end }}
          {{- if .Values.api.events.nats.tokenSecretName }}
            - name: TENANTAPI_EVENTS_NATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.events.nats.tokenSecretName }}
                  key: token
          {{- end }}
          {{- if .Values.api.events.nats.credsSecretName }}
            - name: TENANTAPI_EVENTS_NATS_CREDSFILE
              value: "{{ .Values.api.events.nats.credsFile }}"
          {{- end }}
            - name: TENANTAPI_RUNTIMESOCKET
              value: "unix:///var/iam-runtime/runtime.sock"
          envFrom:
            - secretRef:
                name: {{ .Values.api.db.uriSecret }}
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
          ports:
            - name: http
              containerPort: {{ .Values.api.listenPort | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts: {{- include "iam-runtime-infratographer.volumeMounts" $ | nindent 12 }}
            {{- if .Values.api.events.nats.credsSecretName  }}
            - name: events-creds
              mountPath: /nats
            {{- end }}
            {{- if .Values.api.db.certSecret }}
            - name: dbcerts
              mountPath: "{{ .Values.api.db.certMountPath }}"
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        - {{- include "iam-runtime-infratographer.container" $ | nindent 10 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: {{- include "iam-runtime-infratographer.volumes" $ | nindent 8 }}
        {{- if .Values.api.events.nats.credsSecretName  }}
        - name: events-creds
          secret:
            secretName: "{{ .Values.api.events.nats.credsSecretName }}"
        {{- end }}
        {{- if .Values.api.db.certSecret }}
        - name: dbcerts
          secret:
            secretName: "{{ .Values.api.db.certSecret }}"
        {{- end }}
{{- include "iam-runtime-infratographer.manifests" $ }}
