---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.api.extraLabels }}
    {{- toYaml .Values.api.extraLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.api.extraAnnotations }}
  annotations:
    {{- toYaml .Values.api.extraAnnotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.labels.standard" . | nindent 8 }}
      {{- if .Values.api.extraLabels }}
      {{- toYaml .Values.api.extraLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.api.extraAnnotations }}
      annotations:
        {{- toYaml .Values.api.extraAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.api.migrateOnInit  }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          envFrom:
            - secretRef:
                name: {{ .Values.api.db.uriSecret }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - up
          volumeMounts:
            {{- if .Values.api.db.certSecret }}
            - name: dbcerts
              mountPath: "/dbcerts"
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: TENANTAPI_NATS_URL
              value: "{{ .Values.api.events.connectionURL }}"
            - name: TENANTAPI_NATS_STREAM_NAME
              value: "{{ .Values.api.events.queue | default "tenantapi" }}"
            - name: TENANTAPI_NATS_SUBJECT_PREFIX
              value: "{{ .Values.api.events.subjects }}"
          {{- if .Values.api.events.auth.secretName }}
            - name: TENANTAPI_NATS_CREDS_FILE
              value: "{{ .Values.api.events.credsPath }}"
          {{- end }}
          {{- with .Values.audit.enabled }}
            - name: TENANTAPI_AUDIT_LOG_PATH
              value: "/data/audit/audit.log"
          {{- end }}
          {{- if .Values.api.oidc.enabled }}
          {{- with .Values.api.oidc.audience }}
            - name: TENANTAPI_OIDC_AUDIENCE
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.api.oidc.issuer }}
            - name: TENANTAPI_OIDC_ISSUER
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.api.oidc.jwks.uri }}
            - name: TENANTAPI_OIDC_JWKSURI
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.api.oidc.jwks.remoteTimeout }}
            - name: TENANTAPI_OIDC_JWKSREMOTETIMEOUT
              value: "{{ . }}"
          {{- end }}
          {{- else }}
            - name: TENANTAPI_OIDC_ENABLED
              value: "false"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.db.uriSecret }}
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
          ports:
            - name: http
              containerPort: {{ .Values.api.listenPort | default "8080" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts:
            {{- if .Values.api.events.auth.secretName  }}
            - name: events-creds
              mountPath: /nats
            {{- end }}
            {{- if .Values.api.db.certSecret }}
            - name: dbcerts
              mountPath: "/dbcerts"
              readOnly: true
            {{- end }}
            {{- if .Values.audit.enabled }}
            - name: audit-logs
              mountPath: /data/audit
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- if .Values.audit.enabled }}
      # This is the audit container
        - name: {{ template "common.names.fullname" . }}-audit
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - -f
            - /app-audit/audit.log
          image: "{{ .Values.audit.image.registry }}/{{ .Values.audit.image.repository }}:{{ .Values.audit.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: audit-logs
              mountPath: /app-audit
          {{- with .Values.audit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.api.events.auth.secretName  }}
        - name: events-creds
          secret:
            secretName: "{{ .Values.api.events.auth.secretName }}"
        {{- end }}
        {{- if .Values.api.db.certSecret }}
        - name: dbcerts
          secret:
            secretName: "{{ .Values.api.db.certSecret }}"
        {{- end }}
        {{- if .Values.audit.enabled }}
        - name: audit-logs
          emptyDir: {}
        {{- end }}
