version: '3.8'

networks:
  infradev:

volumes:
  crdb:
    null

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.20-bullseye
        NODE_VERSION: "none"
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - ..:/workspace:cached
    networks:
      - infradev
    # Use "forwardPorts" in **devcontainer.json** to forward a port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  # Environment setup
  create_databases:
    image: cockroachdb/cockroach:latest-v22.1
    restart: on-failure:5
    command: "sql --insecure -e 'CREATE DATABASE IF NOT EXISTS tenantapi_dev;'"
    env_file:
      - .env
    depends_on:
      - crdb
    networks:
      - infradev

  # Required services (databases, etc)
  crdb:
    image: cockroachdb/cockroach:latest-v22.1
    command: start-single-node --insecure
    restart: unless-stopped
    volumes:
      - crdb:/cockroach/cockroach-data
    env_file:
      - .env
    healthcheck:
      test: "curl --fail http://localhost:8080/health?ready=1 || exit 1"
      interval: "2s"
      retries: 3
      start_period: "15s"
      timeout: "5s"
    networks:
      - infradev
